#op# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
target 'DYLTool' do
pod 'YTKNetwork'                            # 网络请求
pod 'ReactiveObjC', '~> 3.1.0'              # RAC
pod 'MJRefresh', '~> 3.1.15.3'              # 刷新控件
pod 'MJExtension',  '~> 3.0'                # 字典转模型
pod 'YYKeyboardManager', '~> 1.0.1'         # 键盘相关
pod 'Masonry', '~> 1.1.0'                   # 约束
pod 'FDFullscreenPopGesture', '~> 1.1'      # 手势
pod 'IQKeyboardManager', '~> 6.1.1'         # 键盘管理
pod 'JPFPSStatus', '~> 0.1.1'               # FPS 检测
pod 'lottie-ios', '~> 2.5.0'                # lottie 动画
pod 'TZImagePickerController', '~> 2.2.2'   # 图片选择器
pod 'HXPhotoPicker', '~> 2.2.0'             # 图片选择器
pod 'RSKImageCropper', '~> 2.1.0'           # 图片裁剪
pod 'pop', '~> 1.0.10'                      # pop 动画
pod 'WCDB', '~> 1.0.6'                      # 数据库操作
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DYLTool

end
